### PR TITLE
travis-ci: update distributives and repositories

### PR DESCRIPTION
**Pull request by Totktonada**
Removed EOL distros, added new ones.

Added 2_2 repository to deploy to.

### CODE REVIEW

**Comment by Totktonada** [comment]
Waiting for https://github.com/tarantool/tarantool/issues/4194

**Review by rtsisyk — APPROVED** [review]

**Comment by rtsisyk** [comment]
Fedora 30 has tarantool-1.7.5.0 in main repo - it should work.

**Comment by Totktonada** [comment]
Rebased the PR on the current master.

BTW, we pushed fedora-30 packages to tarantool repository.

**Comment by Totktonada** [comment]
> Could not find distribution named fedora/30
>
> https://travis-ci.org/tarantool/tarantool/jobs/533702746#L5983

Ouch. I'll contact with packagecloud support.

**Comment by Totktonada** [comment]
Now Fedora 30 is supported by packagecloud and we have tarantool packages deployed.

**Pull request merged**
